// <auto-generated />
using System;
using ApollosLibrary.IDP.Domain.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ApollosLibrary.IDP.Domain.Migrations
{
    [DbContext(typeof(ApollosLibraryIDPContext))]
    partial class ApollosLibraryIDPContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ApollosLibrary.IDP.Domain.Model.ApiResource", b =>
                {
                    b.Property<int>("ApiResourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ApiResourceId"));

                    b.Property<string>("AllowedAccessTokenSigningAlgorithms")
                        .HasColumnType("text");

                    b.Property<LocalDateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<LocalDateTime?>("LastAccessed")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<bool>("NonEditable")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShowInDiscoveryDocument")
                        .HasColumnType("boolean");

                    b.Property<LocalDateTime?>("Updated")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("ApiResourceId");

                    b.ToTable("ApiResources");

                    b.HasData(
                        new
                        {
                            ApiResourceId = 1,
                            Created = new NodaTime.LocalDateTime(2022, 7, 6, 22, 7, 22).PlusNanoseconds(932717700L),
                            Description = "Open ID",
                            DisplayName = "Open ID",
                            Enabled = true,
                            Name = "openid",
                            NonEditable = false,
                            ShowInDiscoveryDocument = true
                        },
                        new
                        {
                            ApiResourceId = 2,
                            Created = new NodaTime.LocalDateTime(2022, 7, 6, 22, 7, 22).PlusNanoseconds(932718400L),
                            Description = "Apollo's Library Website",
                            DisplayName = "Apollo's Library Website",
                            Enabled = true,
                            Name = "apolloslibrarywebsite",
                            NonEditable = false,
                            ShowInDiscoveryDocument = true
                        },
                        new
                        {
                            ApiResourceId = 3,
                            Created = new NodaTime.LocalDateTime(2022, 7, 6, 22, 7, 22).PlusNanoseconds(932718700L),
                            Description = "API in the IDP app to manage users",
                            DisplayName = "User API",
                            Enabled = true,
                            Name = "IdentityServerApi",
                            NonEditable = false,
                            ShowInDiscoveryDocument = true
                        });
                });

            modelBuilder.Entity("ApollosLibrary.IDP.Domain.Model.ApiResourceClaim", b =>
                {
                    b.Property<int>("ApiResourceClaimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ApiResourceClaimId"));

                    b.Property<int>("ApiResourceId")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("ApiResourceClaimId");

                    b.HasIndex("ApiResourceId");

                    b.ToTable("ApiResourceClaims");

                    b.HasData(
                        new
                        {
                            ApiResourceClaimId = 1,
                            ApiResourceId = 1,
                            Type = "role"
                        },
                        new
                        {
                            ApiResourceClaimId = 2,
                            ApiResourceId = 1,
                            Type = "username"
                        },
                        new
                        {
                            ApiResourceClaimId = 3,
                            ApiResourceId = 1,
                            Type = "email"
                        });
                });

            modelBuilder.Entity("ApollosLibrary.IDP.Domain.Model.ApiResourceProperty", b =>
                {
                    b.Property<int>("ApiResourcePropertyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ApiResourcePropertyId"));

                    b.Property<int>("ApiResourceId")
                        .HasColumnType("integer");

                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("ApiResourcePropertyId");

                    b.HasIndex("ApiResourceId");

                    b.ToTable("ApiResourceProperties");
                });

            modelBuilder.Entity("ApollosLibrary.IDP.Domain.Model.ApiResourceScope", b =>
                {
                    b.Property<int>("ApiResourceScopeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ApiResourceScopeId"));

                    b.Property<int>("ApiResourceId")
                        .HasColumnType("integer");

                    b.Property<string>("Scope")
                        .HasColumnType("text");

                    b.HasKey("ApiResourceScopeId");

                    b.HasIndex("ApiResourceId");

                    b.ToTable("ApiResourceScopes");
                });

            modelBuilder.Entity("ApollosLibrary.IDP.Domain.Model.ApiResourceSecret", b =>
                {
                    b.Property<int>("ApiResourceSecretId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ApiResourceSecretId"));

                    b.Property<int>("ApiResourceId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Expiration")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("ApiResourceSecretId");

                    b.HasIndex("ApiResourceId");

                    b.ToTable("ApiResourceSecrets");
                });

            modelBuilder.Entity("ApollosLibrary.IDP.Domain.Model.ApiScope", b =>
                {
                    b.Property<int>("ApiScopeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ApiScopeId"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<bool>("Emphasize")
                        .HasColumnType("boolean");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<bool>("Required")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShowInDiscoveryDocument")
                        .HasColumnType("boolean");

                    b.HasKey("ApiScopeId");

                    b.ToTable("ApiScopes");

                    b.HasData(
                        new
                        {
                            ApiScopeId = 1,
                            Description = "Provides access to the My Library Web API",
                            DisplayName = "Apollo's Library API",
                            Emphasize = false,
                            Enabled = true,
                            Name = "apolloslibraryapi",
                            Required = true,
                            ShowInDiscoveryDocument = true
                        },
                        new
                        {
                            ApiScopeId = 2,
                            Description = "Provides access to the My Library User API in the IDP App",
                            DisplayName = "Apollo's Library User API",
                            Emphasize = false,
                            Enabled = true,
                            Name = "IdentityServerApi",
                            Required = true,
                            ShowInDiscoveryDocument = true
                        });
                });

            modelBuilder.Entity("ApollosLibrary.IDP.Domain.Model.ApiScopeClaim", b =>
                {
                    b.Property<int>("ApiScopeClaimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ApiScopeClaimId"));

                    b.Property<int>("ScopeId")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("ApiScopeClaimId");

                    b.HasIndex("ScopeId");

                    b.ToTable("ApiScopeClaims");
                });

            modelBuilder.Entity("ApollosLibrary.IDP.Domain.Model.ApiScopeProperty", b =>
                {
                    b.Property<int>("ApiScopePropertyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ApiScopePropertyId"));

                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<int>("ScopeId")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("ApiScopePropertyId");

                    b.HasIndex("ScopeId");

                    b.ToTable("ApiScopeProperties");
                });

            modelBuilder.Entity("ApollosLibrary.IDP.Domain.Model.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ClientId"));

                    b.Property<int>("AbsoluteRefreshTokenLifetime")
                        .HasColumnType("integer");

                    b.Property<int>("AccessTokenLifetime")
                        .HasColumnType("integer");

                    b.Property<int>("AccessTokenType")
                        .HasColumnType("integer");

                    b.Property<bool>("AllowAccessTokensViaBrowser")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllowOfflineAccess")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllowPlainTextPkce")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllowRememberConsent")
                        .HasColumnType("boolean");

                    b.Property<string>("AllowedIdentityTokenSigningAlgorithms")
                        .HasColumnType("text");

                    b.Property<bool>("AlwaysIncludeUserClaimsInIdToken")
                        .HasColumnType("boolean");

                    b.Property<bool>("AlwaysSendClientClaims")
                        .HasColumnType("boolean");

                    b.Property<int>("AuthorizationCodeLifetime")
                        .HasColumnType("integer");

                    b.Property<bool>("BackChannelLogoutSessionRequired")
                        .HasColumnType("boolean");

                    b.Property<string>("BackChannelLogoutUri")
                        .HasColumnType("text");

                    b.Property<string>("ClientClaimsPrefix")
                        .HasColumnType("text");

                    b.Property<string>("ClientIdentifier")
                        .HasColumnType("text");

                    b.Property<string>("ClientName")
                        .HasColumnType("text");

                    b.Property<string>("ClientUri")
                        .HasColumnType("text");

                    b.Property<int?>("ConsentLifetime")
                        .HasColumnType("integer");

                    b.Property<LocalDateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DeviceCodeLifetime")
                        .HasColumnType("integer");

                    b.Property<bool>("EnableLocalLogin")
                        .HasColumnType("boolean");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("FrontChannelLogoutSessionRequired")
                        .HasColumnType("boolean");

                    b.Property<string>("FrontChannelLogoutUri")
                        .HasColumnType("text");

                    b.Property<int>("IdentityTokenLifetime")
                        .HasColumnType("integer");

                    b.Property<bool>("IncludeJwtId")
                        .HasColumnType("boolean");

                    b.Property<LocalDateTime?>("LastAccessed")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LogoUri")
                        .HasColumnType("text");

                    b.Property<bool>("NonEditable")
                        .HasColumnType("boolean");

                    b.Property<string>("PairWiseSubjectSalt")
                        .HasColumnType("text");

                    b.Property<string>("ProtocolType")
                        .HasColumnType("text");

                    b.Property<string>("RefreshTokenExpiration")
                        .HasColumnType("text");

                    b.Property<string>("RefreshTokenUsage")
                        .HasColumnType("text");

                    b.Property<bool>("RequireClientSecret")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequireConsent")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequirePkce")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequireRequestObject")
                        .HasColumnType("boolean");

                    b.Property<int>("SlidingRefreshTokenLifetime")
                        .HasColumnType("integer");

                    b.Property<bool>("UpdateAccessTokenClaimsOnRefresh")
                        .HasColumnType("boolean");

                    b.Property<LocalDateTime?>("Updated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UserCodeType")
                        .HasColumnType("text");

                    b.Property<int?>("UserSsoLifetime")
                        .HasColumnType("integer");

                    b.HasKey("ClientId");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            ClientId = 1,
                            AbsoluteRefreshTokenLifetime = 6000,
                            AccessTokenLifetime = 6000,
                            AccessTokenType = 0,
                            AllowAccessTokensViaBrowser = true,
                            AllowOfflineAccess = true,
                            AllowPlainTextPkce = false,
                            AllowRememberConsent = false,
                            AlwaysIncludeUserClaimsInIdToken = true,
                            AlwaysSendClientClaims = true,
                            AuthorizationCodeLifetime = 6000,
                            BackChannelLogoutSessionRequired = true,
                            ClientIdentifier = "apolloslibrarywebapp",
                            ClientName = "Apollo's Library Web App",
                            Created = new NodaTime.LocalDateTime(2022, 7, 6, 22, 7, 22).PlusNanoseconds(932723800L),
                            Description = "Apollo's Library Web App",
                            DeviceCodeLifetime = 6000,
                            EnableLocalLogin = true,
                            Enabled = true,
                            FrontChannelLogoutSessionRequired = true,
                            IdentityTokenLifetime = 6000,
                            IncludeJwtId = true,
                            NonEditable = false,
                            ProtocolType = "oidc",
                            RefreshTokenExpiration = "Sliding",
                            RefreshTokenUsage = "ReUse",
                            RequireClientSecret = false,
                            RequireConsent = false,
                            RequirePkce = true,
                            RequireRequestObject = false,
                            SlidingRefreshTokenLifetime = 6000,
                            UpdateAccessTokenClaimsOnRefresh = true
                        });
                });

            modelBuilder.Entity("ApollosLibrary.IDP.Domain.Model.ClientClaim", b =>
                {
                    b.Property<int>("ClientClaimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ClientClaimId"));

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("ClientClaimId");

                    b.HasIndex("ClientId");

                    b.ToTable("ClientClaims");
                });

            modelBuilder.Entity("ApollosLibrary.IDP.Domain.Model.ClientCorsOrigin", b =>
                {
                    b.Property<int>("ClientCorsOriginId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ClientCorsOriginId"));

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<string>("Origin")
                        .HasColumnType("text");

                    b.HasKey("ClientCorsOriginId");

                    b.HasIndex("ClientId");

                    b.ToTable("ClientCorsOrigins");

                    b.HasData(
                        new
                        {
                            ClientCorsOriginId = 1,
                            ClientId = 1,
                            Origin = "http://localhost:3000"
                        });
                });

            modelBuilder.Entity("ApollosLibrary.IDP.Domain.Model.ClientGrantType", b =>
                {
                    b.Property<int>("ClientGrantTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ClientGrantTypeId"));

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<string>("GrantType")
                        .HasColumnType("text");

                    b.HasKey("ClientGrantTypeId");

                    b.HasIndex("ClientId");

                    b.ToTable("ClientGrantTypes");

                    b.HasData(
                        new
                        {
                            ClientGrantTypeId = 1,
                            ClientId = 1,
                            GrantType = "password"
                        },
                        new
                        {
                            ClientGrantTypeId = 2,
                            ClientId = 1,
                            GrantType = "client_credentials"
                        },
                        new
                        {
                            ClientGrantTypeId = 3,
                            ClientId = 1,
                            GrantType = "implicit"
                        },
                        new
                        {
                            ClientGrantTypeId = 4,
                            ClientId = 1,
                            GrantType = "refresh_token"
                        });
                });

            modelBuilder.Entity("ApollosLibrary.IDP.Domain.Model.ClientIdPrestriction", b =>
                {
                    b.Property<int>("ClientIdPrestrictionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ClientIdPrestrictionId"));

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<string>("Provider")
                        .HasColumnType("text");

                    b.HasKey("ClientIdPrestrictionId");

                    b.HasIndex("ClientId");

                    b.ToTable("ClientIdPrestrictions");
                });

            modelBuilder.Entity("ApollosLibrary.IDP.Domain.Model.ClientPostLogoutRedirectUri", b =>
                {
                    b.Property<int>("ClientPostLogoutRedirectUriId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ClientPostLogoutRedirectUriId"));

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<string>("PostLogoutRedirectUri")
                        .HasColumnType("text");

                    b.HasKey("ClientPostLogoutRedirectUriId");

                    b.HasIndex("ClientId");

                    b.ToTable("ClientPostLogoutRedirectUris");
                });

            modelBuilder.Entity("ApollosLibrary.IDP.Domain.Model.ClientProperty", b =>
                {
                    b.Property<int>("ClientPropertyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ClientPropertyId"));

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("ClientPropertyId");

                    b.HasIndex("ClientId");

                    b.ToTable("ClientProperties");
                });

            modelBuilder.Entity("ApollosLibrary.IDP.Domain.Model.ClientRedirectUri", b =>
                {
                    b.Property<int>("ClientRedirectUriId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ClientRedirectUriId"));

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<string>("RedirectUri")
                        .HasColumnType("text");

                    b.HasKey("ClientRedirectUriId");

                    b.HasIndex("ClientId");

                    b.ToTable("ClientRedirectUris");

                    b.HasData(
                        new
                        {
                            ClientRedirectUriId = 1,
                            ClientId = 1,
                            RedirectUri = "http://localhost:3000/callback"
                        });
                });

            modelBuilder.Entity("ApollosLibrary.IDP.Domain.Model.ClientScope", b =>
                {
                    b.Property<int>("ClientScopeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ClientScopeId"));

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<string>("Scope")
                        .HasColumnType("text");

                    b.HasKey("ClientScopeId");

                    b.HasIndex("ClientId");

                    b.ToTable("ClientScopes");

                    b.HasData(
                        new
                        {
                            ClientScopeId = 1,
                            ClientId = 1,
                            Scope = "openid"
                        },
                        new
                        {
                            ClientScopeId = 2,
                            ClientId = 1,
                            Scope = "profile"
                        },
                        new
                        {
                            ClientScopeId = 3,
                            ClientId = 1,
                            Scope = "apolloslibraryapi"
                        },
                        new
                        {
                            ClientScopeId = 4,
                            ClientId = 1,
                            Scope = "role"
                        },
                        new
                        {
                            ClientScopeId = 5,
                            ClientId = 1,
                            Scope = "username"
                        },
                        new
                        {
                            ClientScopeId = 6,
                            ClientId = 1,
                            Scope = "email"
                        },
                        new
                        {
                            ClientScopeId = 7,
                            ClientId = 1,
                            Scope = "offline_access"
                        },
                        new
                        {
                            ClientScopeId = 8,
                            ClientId = 1,
                            Scope = "IdentityServerApi"
                        });
                });

            modelBuilder.Entity("ApollosLibrary.IDP.Domain.Model.ClientSecret", b =>
                {
                    b.Property<int>("ClientSecretId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ClientSecretId"));

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<LocalDateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<LocalDateTime?>("Expiration")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("ClientSecretId");

                    b.HasIndex("ClientId");

                    b.ToTable("ClientSecrets");

                    b.HasData(
                        new
                        {
                            ClientSecretId = 1,
                            ClientId = 1,
                            Created = new NodaTime.LocalDateTime(2022, 7, 6, 22, 7, 22).PlusNanoseconds(932737100L),
                            Description = "apolloslibrarywebsite",
                            Type = "SharedSecret",
                            Value = "979eb386dc9a387d614b72902e44f5cb295636d71f829d2afccff401eb794bd6"
                        });
                });

            modelBuilder.Entity("ApollosLibrary.IDP.Domain.Model.DeviceCode", b =>
                {
                    b.Property<string>("DeviceCodeId")
                        .HasColumnType("text");

                    b.Property<string>("ClientId")
                        .HasColumnType("text");

                    b.Property<LocalDateTime>("CreationTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Data")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<LocalDateTime>("Expiration")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("SessionId")
                        .HasColumnType("text");

                    b.Property<string>("SubjectId")
                        .HasColumnType("text");

                    b.Property<string>("UserCode")
                        .HasColumnType("text");

                    b.HasKey("DeviceCodeId");

                    b.ToTable("DeviceCodes");
                });

            modelBuilder.Entity("ApollosLibrary.IDP.Domain.Model.IdentityResource", b =>
                {
                    b.Property<int>("IdentityResourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdentityResourceId"));

                    b.Property<LocalDateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<bool>("Emphasize")
                        .HasColumnType("boolean");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<bool>("NonEditable")
                        .HasColumnType("boolean");

                    b.Property<bool>("Required")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShowInDiscoveryDocument")
                        .HasColumnType("boolean");

                    b.Property<LocalDateTime?>("Updated")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("IdentityResourceId");

                    b.ToTable("IdentityResources");

                    b.HasData(
                        new
                        {
                            IdentityResourceId = 1,
                            Created = new NodaTime.LocalDateTime(2022, 7, 6, 22, 7, 22).PlusNanoseconds(932743300L),
                            Description = "openid",
                            DisplayName = "Opend ID",
                            Emphasize = false,
                            Enabled = true,
                            Name = "openid",
                            NonEditable = false,
                            Required = true,
                            ShowInDiscoveryDocument = true
                        },
                        new
                        {
                            IdentityResourceId = 2,
                            Created = new NodaTime.LocalDateTime(2022, 7, 6, 22, 7, 22).PlusNanoseconds(932744100L),
                            Description = "User claims",
                            DisplayName = "User Claims",
                            Emphasize = false,
                            Enabled = true,
                            Name = "claims",
                            NonEditable = false,
                            Required = true,
                            ShowInDiscoveryDocument = true
                        },
                        new
                        {
                            IdentityResourceId = 3,
                            Created = new NodaTime.LocalDateTime(2022, 7, 6, 22, 7, 22).PlusNanoseconds(932744400L),
                            Description = "User Profile",
                            DisplayName = "User Profile",
                            Emphasize = false,
                            Enabled = true,
                            Name = "profile",
                            NonEditable = false,
                            Required = true,
                            ShowInDiscoveryDocument = true
                        },
                        new
                        {
                            IdentityResourceId = 4,
                            Created = new NodaTime.LocalDateTime(2022, 7, 6, 22, 7, 22).PlusNanoseconds(932744600L),
                            Description = "Username",
                            DisplayName = "Username",
                            Emphasize = false,
                            Enabled = true,
                            Name = "username",
                            NonEditable = false,
                            Required = true,
                            ShowInDiscoveryDocument = true
                        },
                        new
                        {
                            IdentityResourceId = 5,
                            Created = new NodaTime.LocalDateTime(2022, 7, 6, 22, 7, 22).PlusNanoseconds(932744900L),
                            Description = "User Role",
                            DisplayName = "User Role",
                            Emphasize = false,
                            Enabled = true,
                            Name = "role",
                            NonEditable = false,
                            Required = true,
                            ShowInDiscoveryDocument = true
                        },
                        new
                        {
                            IdentityResourceId = 6,
                            Created = new NodaTime.LocalDateTime(2022, 7, 6, 22, 7, 22).PlusNanoseconds(932745300L),
                            Description = "User Email",
                            DisplayName = "User Email",
                            Emphasize = false,
                            Enabled = true,
                            Name = "email",
                            NonEditable = false,
                            Required = true,
                            ShowInDiscoveryDocument = true
                        });
                });

            modelBuilder.Entity("ApollosLibrary.IDP.Domain.Model.IdentityResourceClaim", b =>
                {
                    b.Property<int>("IdentityResourceClaimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdentityResourceClaimId"));

                    b.Property<int>("IdentityResourceId")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("IdentityResourceClaimId");

                    b.HasIndex("IdentityResourceId");

                    b.ToTable("IdentityResourceClaims");
                });

            modelBuilder.Entity("ApollosLibrary.IDP.Domain.Model.IdentityResourceProperty", b =>
                {
                    b.Property<int>("IdentityResourcePropertyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdentityResourcePropertyId"));

                    b.Property<int>("IdentityResourceId")
                        .HasColumnType("integer");

                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("IdentityResourcePropertyId");

                    b.HasIndex("IdentityResourceId");

                    b.ToTable("IdentityResourceProperties");
                });

            modelBuilder.Entity("ApollosLibrary.IDP.Domain.Model.PersistedGrant", b =>
                {
                    b.Property<string>("PersistedGrantKey")
                        .HasColumnType("text");

                    b.Property<string>("ClientId")
                        .HasColumnType("text");

                    b.Property<LocalDateTime?>("ConsumedTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<LocalDateTime>("CreationTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Data")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<LocalDateTime?>("Expiration")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("SessionId")
                        .HasColumnType("text");

                    b.Property<string>("SubjectId")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("PersistedGrantKey");

                    b.ToTable("PersistedGrants");
                });

            modelBuilder.Entity("ApollosLibrary.IDP.Domain.Model.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<LocalDateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<LocalDateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("SecurityCode")
                        .HasColumnType("text");

                    b.Property<LocalDateTime?>("SecurityCodeExpirationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Subject")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("e7f12974-73dd-48d6-aa79-95fe1ded101e"),
                            CreatedBy = new Guid("e7f12974-73dd-48d6-aa79-95fe1ded101e"),
                            CreatedDate = new NodaTime.LocalDateTime(2022, 7, 6, 22, 7, 22).PlusNanoseconds(932695400L),
                            IsActive = true,
                            IsBanned = false,
                            Password = "AQAAAAEAACcQAAAAECY64tCZ5CSbcXzOp4NE6XAr1TB9wQ1zgMv6Sa49QGTmEftnFXzPMsBH+NB1cu5brw==",
                            Subject = "a3808d45-d88b-4100-bd40-4c75bcb61d00",
                            Username = "radulfr"
                        });
                });

            modelBuilder.Entity("ApollosLibrary.IDP.Domain.Model.UserClaim", b =>
                {
                    b.Property<Guid>("UserClaimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserClaimId");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims");

                    b.HasData(
                        new
                        {
                            UserClaimId = new Guid("93908216-6759-47d4-9417-71f6523318da"),
                            Type = "role",
                            UserId = new Guid("e7f12974-73dd-48d6-aa79-95fe1ded101e"),
                            Value = "administrator"
                        },
                        new
                        {
                            UserClaimId = new Guid("1fec9ba0-aa2c-478f-89cf-4f792cd28901"),
                            Type = "role",
                            UserId = new Guid("e7f12974-73dd-48d6-aa79-95fe1ded101e"),
                            Value = "moderator"
                        },
                        new
                        {
                            UserClaimId = new Guid("3e548e7f-1f31-45b3-a92a-ee49e42ddae1"),
                            Type = "emailaddress",
                            UserId = new Guid("e7f12974-73dd-48d6-aa79-95fe1ded101e"),
                            Value = "wados.russell70@gmail.com"
                        });
                });

            modelBuilder.Entity("ApollosLibrary.IDP.Domain.Model.ApiResourceClaim", b =>
                {
                    b.HasOne("ApollosLibrary.IDP.Domain.Model.ApiResource", "ApiResource")
                        .WithMany("ApiResourceClaims")
                        .HasForeignKey("ApiResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApiResource");
                });

            modelBuilder.Entity("ApollosLibrary.IDP.Domain.Model.ApiResourceProperty", b =>
                {
                    b.HasOne("ApollosLibrary.IDP.Domain.Model.ApiResource", "ApiResource")
                        .WithMany("ApiResourceProperties")
                        .HasForeignKey("ApiResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApiResource");
                });

            modelBuilder.Entity("ApollosLibrary.IDP.Domain.Model.ApiResourceScope", b =>
                {
                    b.HasOne("ApollosLibrary.IDP.Domain.Model.ApiResource", "ApiResource")
                        .WithMany("ApiResourceScopes")
                        .HasForeignKey("ApiResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApiResource");
                });

            modelBuilder.Entity("ApollosLibrary.IDP.Domain.Model.ApiResourceSecret", b =>
                {
                    b.HasOne("ApollosLibrary.IDP.Domain.Model.ApiResource", "ApiResource")
                        .WithMany("ApiResourceSecrets")
                        .HasForeignKey("ApiResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApiResource");
                });

            modelBuilder.Entity("ApollosLibrary.IDP.Domain.Model.ApiScopeClaim", b =>
                {
                    b.HasOne("ApollosLibrary.IDP.Domain.Model.ApiScope", "Scope")
                        .WithMany("ApiScopeClaims")
                        .HasForeignKey("ScopeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scope");
                });

            modelBuilder.Entity("ApollosLibrary.IDP.Domain.Model.ApiScopeProperty", b =>
                {
                    b.HasOne("ApollosLibrary.IDP.Domain.Model.ApiScope", "Scope")
                        .WithMany("ApiScopeProperties")
                        .HasForeignKey("ScopeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scope");
                });

            modelBuilder.Entity("ApollosLibrary.IDP.Domain.Model.ClientClaim", b =>
                {
                    b.HasOne("ApollosLibrary.IDP.Domain.Model.Client", "Client")
                        .WithMany("ClientClaims")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("ApollosLibrary.IDP.Domain.Model.ClientCorsOrigin", b =>
                {
                    b.HasOne("ApollosLibrary.IDP.Domain.Model.Client", "Client")
                        .WithMany("ClientCorsOrigins")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("ApollosLibrary.IDP.Domain.Model.ClientGrantType", b =>
                {
                    b.HasOne("ApollosLibrary.IDP.Domain.Model.Client", "Client")
                        .WithMany("ClientGrantTypes")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("ApollosLibrary.IDP.Domain.Model.ClientIdPrestriction", b =>
                {
                    b.HasOne("ApollosLibrary.IDP.Domain.Model.Client", "Client")
                        .WithMany("ClientIdPrestrictions")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("ApollosLibrary.IDP.Domain.Model.ClientPostLogoutRedirectUri", b =>
                {
                    b.HasOne("ApollosLibrary.IDP.Domain.Model.Client", "Client")
                        .WithMany("ClientPostLogoutRedirectUris")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("ApollosLibrary.IDP.Domain.Model.ClientProperty", b =>
                {
                    b.HasOne("ApollosLibrary.IDP.Domain.Model.Client", "Client")
                        .WithMany("ClientProperties")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("ApollosLibrary.IDP.Domain.Model.ClientRedirectUri", b =>
                {
                    b.HasOne("ApollosLibrary.IDP.Domain.Model.Client", "Client")
                        .WithMany("ClientRedirectUris")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("ApollosLibrary.IDP.Domain.Model.ClientScope", b =>
                {
                    b.HasOne("ApollosLibrary.IDP.Domain.Model.Client", "Client")
                        .WithMany("ClientScopes")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("ApollosLibrary.IDP.Domain.Model.ClientSecret", b =>
                {
                    b.HasOne("ApollosLibrary.IDP.Domain.Model.Client", "Client")
                        .WithMany("ClientSecrets")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("ApollosLibrary.IDP.Domain.Model.IdentityResourceClaim", b =>
                {
                    b.HasOne("ApollosLibrary.IDP.Domain.Model.IdentityResource", "IdentityResource")
                        .WithMany("IdentityResourceClaims")
                        .HasForeignKey("IdentityResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdentityResource");
                });

            modelBuilder.Entity("ApollosLibrary.IDP.Domain.Model.IdentityResourceProperty", b =>
                {
                    b.HasOne("ApollosLibrary.IDP.Domain.Model.IdentityResource", "IdentityResource")
                        .WithMany("IdentityResourceProperties")
                        .HasForeignKey("IdentityResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdentityResource");
                });

            modelBuilder.Entity("ApollosLibrary.IDP.Domain.Model.UserClaim", b =>
                {
                    b.HasOne("ApollosLibrary.IDP.Domain.Model.User", "User")
                        .WithMany("UserClaims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ApollosLibrary.IDP.Domain.Model.ApiResource", b =>
                {
                    b.Navigation("ApiResourceClaims");

                    b.Navigation("ApiResourceProperties");

                    b.Navigation("ApiResourceScopes");

                    b.Navigation("ApiResourceSecrets");
                });

            modelBuilder.Entity("ApollosLibrary.IDP.Domain.Model.ApiScope", b =>
                {
                    b.Navigation("ApiScopeClaims");

                    b.Navigation("ApiScopeProperties");
                });

            modelBuilder.Entity("ApollosLibrary.IDP.Domain.Model.Client", b =>
                {
                    b.Navigation("ClientClaims");

                    b.Navigation("ClientCorsOrigins");

                    b.Navigation("ClientGrantTypes");

                    b.Navigation("ClientIdPrestrictions");

                    b.Navigation("ClientPostLogoutRedirectUris");

                    b.Navigation("ClientProperties");

                    b.Navigation("ClientRedirectUris");

                    b.Navigation("ClientScopes");

                    b.Navigation("ClientSecrets");
                });

            modelBuilder.Entity("ApollosLibrary.IDP.Domain.Model.IdentityResource", b =>
                {
                    b.Navigation("IdentityResourceClaims");

                    b.Navigation("IdentityResourceProperties");
                });

            modelBuilder.Entity("ApollosLibrary.IDP.Domain.Model.User", b =>
                {
                    b.Navigation("UserClaims");
                });
#pragma warning restore 612, 618
        }
    }
}
